..

diff --git a/prompt3 b/prompt3
--- a/prompt3
+++ b/prompt3
@@ -1,4 +1,23 @@
 #!/bin/bash
 
-PS0="$?"
-PS1="\[\e[5;92m\]\$(date +'%H:%M')\[\e[0m\] \[\033[01;34m\]\w\[\033[00m\] \[\e[5m\]⚡\[\e[0m\]"
+reset="\[\e[0m\]"
+white="\[\e[97m\]"
+red="\[\e[31m\]"
+
+# Function to set the color of the dollar sign based on the exit code
+set_dollar_color() {
+    if [ $? -ne 0 ]; then
+        dollar_color="$red"  # Set dollar sign color to red
+    else
+        dollar_color="$white"  # Set dollar sign color to white
+    fi
+}
+
+# Set the PROMPT_COMMAND to run the function after every command
+PROMPT_COMMAND='set_dollar_color'
+
+# Set PS0 prompt
+PS0="\e[33m$?\e[0m\n"
+
+# Set PS1 prompt
+PS1="\[\e[92m\]\$(date +'%H:%M')\[\e[0m\] \[\033[01;34m\]\w\[\033[00m\] $dollar_color\$ $reset"
